export default {
  SPLASHSCREEN: 'SplashScreen',
  LOGINSCREEN: 'LoginScreen',
  SIGNUPSCREEN: 'SignUpScreen',
  VERIFYOTPSCREEN: 'VerifyOtpScreen',
  PROFILESTACK: 'ProfileStack',
  HOMESTACK: 'HomeStack',
  SELLSTACK: 'SellStack',
  PROFILESCREEN: 'ProfileScreen',
  HOMESCREEN: 'HomeScreen',
  SELLSCREEN: 'SellScreen',
  BOTTOMTAB: 'BottomTab',
  PRODUCTDETAILSCREEN: 'ProductDetailScreen',
  CATEGORYLISTSCREEN: 'CategoryListScreen',
};
